name: release
on:
  workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Build Dependencies
        run: sudo apt -qq update && sudo apt -yy -qq install make gcc libgtk-3-dev libayatana-appindicator3-dev golang-1.18
      - name: Setup
        run: make setup
      - name: Test
        run: make test
      - name: Build
        run: make build
      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}